package feo.health.ai.domain.model.response

/**
 * Domain response entity containing recommendations dynamically generated by AI matching.
 *
 * @property doctors List of recommended doctor specialties.
 * @property drugs List of recommended drug medications.
 * @property possibleDiseases Map of possible diseases mapped to probability percentages values.
 * @property generalAnswer Natural language recommendations response summary output.
 */
data class FeatureSuggestionResponseDomain(
    val doctors: List<String>,
    val drugs: List<String>,
    val possibleDiseases: Map<String, Double>,
    val generalAnswer: String
)
