package feo.health.ai.dto.response

import kotlinx.serialization.Serializable

/**
 * Data transfer response object containing recommendations dynamically generated by AI matching.
 *
 * @property doctors List of recommended doctor specialties.
 * @property drugs List of recommended drug medications.
 * @property possibleDiseases Map of possible diseases mapped to probability percentages values.
 * @property generalAnswer Natural language recommendations response summary output.
 */
@Serializable
data class SuggestionResponse(
    val doctors: List<String>,
    val drugs: List<String>,
    val possibleDiseases: Map<String, Double>,
    val generalAnswer: String
)
